http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.1.0.2 

prometheus:
  namespace: hass
  requires_auth: false

recorder:
  auto_purge: true
  purge_keep_days: 15
  db_url: !secret db_url
  db_retry_wait: 15

template:
  - sensor:
      - name: "weather_forecast_wind_speed"
        unit_of_measurement: "km/h"
        state: "{{ state_attr('weather.forecast_maison', 'wind_speed') }}"
      - name: "weather_forecast_temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('weather.forecast_maison', 'temperature') }}"
      - name: "electricity_consumption_prise_connectee_salon_consommation_actuelle"
        unit_of_measurement: "W"
        state: "{{ states.sensor.prise_connectee_salon_consommation_actuelle.state }}"
      - name: "electricity_consumption_prise_connectee_chambre_hugo_consommation_actuelle"
        unit_of_measurement: "W"
        state: "{{ states.sensor.prise_connectee_chambre_hugo_consommation_actuelle.state }}"
      - name: "electricity_consumption_prise_connectee_chambre_parents_consommation_actuelle"
        unit_of_measurement: "W"
        state: "{{ states.sensor.prise_connectee_chambre_parents_consommation_actuelle.state }}"

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  packages: !include_dir_merge_named packages
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
