groups:
- name: swimming-pool
  rules:
  # Temperature
  - alert: SwimmingPoolTemperatureSaturationVeryLow
    expr: 'homeassistant_swimming_pool_temperature <= 15'
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Swimming pool Temperature saturation is very low
      description: Swimming pool Temperature saturation very is low
  - alert: SwimmingPoolTemperatureSaturationLow
    expr: 'homeassistant_swimming_pool_temperature > 15 and homeassistant_swimming_pool_temperature < 20.5'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Swimming pool Temperature saturation is low
      description: Swimming pool Temperature saturation is low
  - alert: SwimmingPoolTemperatureSaturationHigh
    expr: 'homeassistant_swimming_pool_temperature > 29 and homeassistant_swimming_pool_temperature < 32'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Swimming pool Temperature saturation is high
      description: Swimming pool Temperature saturation is high
  - alert: SwimmingPoolTemperatureSaturationVeryHigh
    expr: 'homeassistant_swimming_pool_temperature >= 32'
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Swimming pool Temperature saturation is very high
      description: Swimming pool Temperature saturation very is high
  # ORP
  - alert: SwimmingPoolORPSaturationVeryLow
    expr: 'homeassistant_swimming_pool_orp <= 550'
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Swimming pool ORP saturation is very low
      description: Swimming pool ORP saturation very is low
  - alert: SwimmingPoolORPSaturationLow
    expr: 'homeassistant_swimming_pool_orp > 550 and homeassistant_swimming_pool_orp < 650'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Swimming pool ORP saturation is low
      description: Swimming pool ORP saturation is low
  - alert: SwimmingPoolORPSaturationHigh
    expr: 'homeassistant_swimming_pool_orp > 800 and homeassistant_swimming_pool_orp < 1000'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Swimming pool ORP saturation is high
      description: Swimming pool ORP saturation is high
  - alert: SwimmingPoolORPSaturationVeryHigh
    expr: 'homeassistant_swimming_pool_orp >= 1000'
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Swimming pool ORP saturation is very high
      description: Swimming pool ORP saturation very is high
  # PH
  - alert: SwimmingPoolPHSaturationVeryLow
    expr: 'homeassistant_swimming_pool_ph <= 6.8'
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Swimming pool PH saturation is very low
      description: Swimming pool PH saturation very is low
  - alert: SwimmingPoolPHSaturationLow
    expr: 'homeassistant_swimming_pool_ph > 6.8 and homeassistant_swimming_pool_ph < 7.1'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Swimming pool PH saturation is low
      description: Swimming pool PH saturation is low
  - alert: SwimmingPoolPHSaturationHigh
    expr: 'homeassistant_swimming_pool_ph > 7.7 and homeassistant_swimming_pool_ph < 8.1'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Swimming pool PH saturation is high
      description: Swimming pool PH saturation is high
  - alert: SwimmingPoolPHSaturationVeryHigh
    expr: 'homeassistant_swimming_pool_ph >= 8.1'
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Swimming pool PH saturation is very high
      description: Swimming pool PH saturation very is high
